modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
[[mods]]
modId = "poscendo"
version = "${file.jarVersion}"
displayName = "Poscendo"
updateJSONURL="https://api.modrinth.com/updates/poscendo/forge_updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/poscendo/"
logoFile="logo.png"
credits="Art and logo done by _JWX!"
authors="MiteBeMana"

description = '''
A configurable clientside mod adding various tweaks to potions.
'''

[[dependencies.poscendo]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.poscendo]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
